### ISSUE TITLE
GSP-30 지라 연동 테스트

### ISSUE THREAD

**Issue by youhyeoneee** [youhyeoneee/geumsapa#5]
### 상위 작업 Ticket Number

GSP-2

### 브랜치 이름 (이슈 요약)

jira-test

### 브랜치 전략(GitFlow)

chore

### 상세 내용(Details)

- Jira & Github Issue 연동

### 체크리스트(Tasks)

- [x] jira 생성
- [x] issue_template 작성 
- [x] workflow main.yml 작성

**Comment by youhyeoneee** [comment]
403 with `remote: Permission to xxx.git denied to github-actions[bot].`

해결 방법 >> https://wnsdufdl.tistory.com/554?category=1014127#google_vignette

**Comment by youhyeoneee** [comment]
```yml
- name: Close Jira issue
    if: env.JIRA_KEY != ''
    uses: atlassian/gajira-transition@v3
    with:
      issue: ${{ env.JIRA_KEY }}
      transition: 완료 # Done 에서 변경
```
transition을 한국어로 바꿔주니 성공하였다.

[프로젝트에서-Jira-사용하기-4-Github-Actions로-GithubJira-이슈-자동화](https://lamerry.tistory.com/entry/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%EC%84%9C-Jira-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-4-Github-Actions%EB%A1%9C-GithubJira-%EC%9D%B4%EC%8A%88-%EC%9E%90%EB%8F%99%ED%99%94)
